<?php
/**
 * @author 2hatslogic
 * @copyright Copyright (c) 2023 2hatslogic (https://www.2hatslogic.com)
 * @package Hatslogic_Referrer
 */

?>
<?php
/**
 * @var $block \Hatslogic\Referrer\Block\SuccessReferal
 */
?>
<?php
$orderId = $block->getOrderId();
$displayPages = $block->getAllDisplayPages();
if (in_array($block->getDisplayArea(), $displayPages)
&& count($block->getReferralOptions()) > 1
&& $block->isEnabled() && $block->checkReferral($orderId)):?>
    <div style="width:20%;margin-top:1em">
        <?php if ($block->canTitleBeDisplayed()):?>
            <label class="label" for="referrer"><?=/*noEscape*/ $block->getReferrerTitle(); ?></label>
        <?php endif; ?>
        <form action=<?= /*noEscape*/ $block->getUrl("hlreferrer/success/referralsuccess"); ?> method="post">
            <?php  $options = $block->getReferralOptions();  ?>
                <select name="referral" <?= $block->getRequired() ?'required' : '';?>>
                    <?php foreach ($options as $option):?>
                    <option value=<?= /*noEscape*/ $option['value'] ?>><?= /*noEscape*/ $option['label'] ?></option>
                    <?php endforeach ?>;
                </select>
                <button style="margin-top:1em" type="submit">Choose Referrer</button>
        </form>
    </div>
<?php endif ?>
