<?php
/**
 * @author 2hatslogic
 * @copyright Copyright (c) 2023 2hatslogic (https://www.2hatslogic.com)
 * @package Hatslogic_Referrer
 */

?>
<?php
/**
 * Ship to multiple address template
 *
 * @var $block \Hatslogic\Referrer\Block\Checkout\Addresses
 */
?>
<form id="checkout_multishipping_form"
      data-mage-init='{
          "multiShipping":{},
          "cartUpdate": {
               "validationURL": "<?= $block->escapeUrl($block->getUrl('multishipping/checkout/checkItems')) ?>",
               "eventName": "updateMulticartItemQty"
          }}'
      action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
      method="post"
      class="multicheckout address form">
    <div class="title">
        <strong><?= $block->escapeHtml(__('Please select a shipping address for applicable items.')) ?></strong>
    </div>
    <input type="hidden" name="continue" value="0" id="can_continue_flag"/>
    <input type="hidden" name="new_address" value="0" id="add_new_address_flag"/>
    <div class="table-wrapper">
        <table class="items data table" id="multiship-addresses-table">
            <caption class="table-caption">
                <?= $block->escapeHtml(__('Please select a shipping address for applicable items.')) ?>
            </caption>
            <thead>
            <tr>
                <th class="col product" scope="col"><?= $block->escapeHtml(__('Product')) ?></th>
                <th class="col qty" scope="col"><?= $block->escapeHtml(__('Qty')) ?></th>
                <th class="col address" scope="col"><?= $block->escapeHtml(__('Send To')) ?></th>
                <th class="col actions" scope="col">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($block->getItems() as $_index => $_item) : ?>
                <?php if ($_item->getQuoteItem()) : ?>
                    <tr>
                        <td class="col product" data-th="<?= $block->escapeHtmlAttr(__('Product')) ?>">
                            <?= $block->getItemHtml($_item->getQuoteItem()) ?>
                        </td>
                        <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
                            <div class="field qty">
                                <label for="ship-<?= $block->escapeHtml($_index) ?>-<?= $block->escapeHtml($_item->getQuoteItemId()) ?>-qty"
                                       class="label">
                                    <span><?= $block->escapeHtml(__('Qty')) ?></span>
                                </label>
                                <div class="control">
                                    <input type="number"
                                           data-multiship-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                           id="ship-<?= $block->escapeHtml($_index) ?>-<?= $block->escapeHtml($_item->getQuoteItemId()) ?>-qty"
                                           name="ship[<?= $block->escapeHtml($_index) ?>][<?= $block->escapeHtml($_item->getQuoteItemId()) ?>][qty]"
                                           value="<?= $block->escapeHtmlAttr($_item->getQty()) ?>"
                                           size="2"
                                           min="0"
                                           class="input-text qty"
                                           data-validate="{number: true, required:true, 'validate-greater-than-zero':true}"/>
                                </div>
                            </div>
                        </td>
                        <td class="col address" data-th="<?= $block->escapeHtmlAttr(__('Send To')) ?>">
                            <?php if ($_item->getProduct()->getIsVirtual()) : ?>
                                <div class="applicable">
                                    <?= $block->escapeHtml(__('A shipping selection is not applicable.')) ?>
                                </div>
                            <?php else : ?>
                                <div class="field address">
                                    <label for="ship_<?= $block->escapeHtml($_index) ?>_<?= $block->escapeHtml($_item->getQuoteItemId()) ?>_address"
                                           class="label">
                                        <span><?= $block->escapeHtml(__('Send To')) ?></span>
                                    </label>
                                    <div class="control">
                                        <?= $block->getAddressesHtmlSelect($_item, $_index) ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </td>
                        <td class="col actions" data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>">
                            <a href="<?= $block->escapeUrl($block->getItemDeleteUrl($_item)) ?>"
                               title="<?= $block->escapeHtmlAttr(__('Remove Item')) ?>"
                               class="action delete"
                               data-multiship-item-remove="">
                                <span><?= $block->escapeHtml(__('Remove item')) ?></span>
                            </a>
                        </td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->isEnabled() && count($block->getReferrerOptions()) >= 1):?>
        <div class="field _required referrer-container">
            <?php if ($block->getConfig('hlreferrer/general/display_title')): ?>
                <label class="label" for="referrer">
                    <span><?= /*noEscape*/ $block->getConfig('hlreferrer/general/referrer_title'); ?></span>
                </label>
            <?php endif;?>
            <div class="control">
                <select class="select" name="referrer" id="referrer"
                    <?php if ($block->getConfig('hlreferrer/general/required')): ?>
                        data-validate="{required:true}">
                    <?php endif;?>
                    <?php foreach ($block->getReferrerOptions() as $key => $option): ?>
                        <option data-title="<?= /*noEscape*/ $option['label'] ?>"
                        <?php if ($block->getReferrerValue() == $option['value']):?>
                            selected="selected"
                        <?php endif;?>
                        value="<?= /*noEscape*/ $option['value'] ?>">
                            <?= /*noEscape*/ $option['label'] ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endif;?>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr(__('Go to Shipping Information')) ?>"
                    class="action primary continue<?= $block->isContinueDisabled() ? ' disabled' : '' ?>"
                    data-role="can-continue"
                    data-flag="1"
                <?php if ($block->isContinueDisabled()) : ?>
                    disabled="disabled"
                <?php endif; ?>>
                <span><?= $block->escapeHtml(__('Go to Shipping Information')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <button type="submit"
                    data-multiship-item-update=""
                    class="action update"
                    data-role="can-continue"
                    data-flag="0">
                <span><?= $block->escapeHtml(__('Update Qty &amp; Addresses')) ?></span>
            </button>
            <button type="button"
                    title="<?= $block->escapeHtmlAttr(__('Enter a New Address')) ?>"
                    class="action add"
                    data-role="add-new-address">
                <span><?= $block->escapeHtml(__('Enter a New Address')) ?></span>
            </button>
            <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
               class="action back">
                <span><?= $block->escapeHtml(__('Back to Shopping Cart')) ?></span>
            </a>
        </div>
    </div>
</form>
<style type="text/css">
    .referrer-container {
        width: 30%;
        margin: 20px 0;
    }
    @media only screen and (max-width: 639px) {
      .referrer-container {
        width: 100%;
      }
    }
</style>